#!/bin/env bash
#$ -S /bin/bash
#$ -o /home/tarsuslam/BlotoMouseRNAseqStatinArm/FastqTrimmed/
#$ -e /home/tarsuslam/BlotoMouseRNAseqStatinArm/FastqTrimmed/
#$ -cwd
#$ -pe smp 8
#$ -r y
#$ -j y
#$ -l mem_free=5G
#$ -l h_rt=20:00:00

TRIMMOMATIC_JAR="Trimmomatic-0.39/trimmomatic-0.39.jar"
ADAPTERS_PATH="Trimmomatic-0.39/adapters/TruSeq3-PE-2.fa"

for file in N*_L004_R1_001.fastq.gz; do
	base=$(basename "$file" _R1_001.fastq.gz)
	java -jar $TRIMMOMATIC_JAR PE -threads 8 -phred33 \
		"$base"_R1_001.fastq.gz "$base"_R2_001.fastq.gz \
		FastqTrimmed/"$base"_R1_trimmed.fastq.gz FastqTrimmed/"$base"_R1_unpaired.fastq.gz \
		FastqTrimmed/"$base"_R2_trimmed.fastq.gz FastqTrimmed/"$base"_R2_unpaired.fastq.gz \
		ILLUMINACLIP:${ADAPTERS_PATH}:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36
done
